stages:
  - build
  - deploy

variables:
  DOCKER_API_VERSION: "1.44"  
  image: docker:26.1.4 


.build_template:
  stage: build
  tags:
    - linux
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE:${SERVICE_NAME}-latest ./${SERVICE_NAME}/
    - docker push $CI_REGISTRY_IMAGE:${SERVICE_NAME}-latest

.deploy_template:
  stage: deploy
  image: curlimages/curl:latest
  tags:
    - linux
  script:
    - |
      curl -H "Authorization: Bearer $WATCHTOWER_TOKEN" \
        -X POST "http://$PRODUCTION_IP:8080/v1/update?container=${SERVICE_NAME}-app"

# NOTE: Parallel matrix is avoided here because GitLab CI does not support 
# dynamic CI_COMMIT_BRANCH changes tracking inside matrix loops.
# Individual jobs ensure that only modified services are built and deployed.

build_python:
  extends: .build_template
  variables:
    SERVICE_NAME: "python"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - python/**/*

deploy_python:
  extends: .deploy_template
  variables:
    SERVICE_NAME: "python"
  needs: ["build_python"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - python/**/*


build_go:
  extends: .build_template
  variables:
    SERVICE_NAME: "go"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - go/**/*

deploy_go:
  extends: .deploy_template
  variables:
    SERVICE_NAME: "go"
  needs: ["build_go"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - go/**/*


build_nodejs:
  extends: .build_template
  variables:
    SERVICE_NAME: "nodejs"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - nodejs/**/*

deploy_nodejs:
  extends: .deploy_template
  variables:
    SERVICE_NAME: "nodejs"
  needs: ["build_nodejs"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - nodejs/**/*
