image: docker:20.10.16

options: 
  docker: true

pipelines:
  branches:
    main:
    - step:
        name: Build, Push to Bitbucket Registry and Deploy
        script:
          - |
            REGISTRY="crg.apkg.io"
            WORKSPACE="lab"

            docker login $REGISTRY -u "$BITBUCKET_PACKAGES_USERNAME" -p "$BITBUCKET_PACKAGES_TOKEN"
            docker buildx create --use --driver docker-container || true
            docker buildx use default

            TARGET_COMMIT=${BITBUCKET_PREV_COMMIT:-"HEAD~1"}
            echo "Comparing $BITBUCKET_COMMIT with $TARGET_COMMIT"
            CHANGED_FILES=$(git diff --name-only $TARGET_COMMIT $BITBUCKET_COMMIT)

            for SERVICE in python go nodejs; do
              if echo "$CHANGED_FILES" | grep -q "^${SERVICE}/"; then
                TAG="${REGISTRY}/${WORKSPACE}/${BITBUCKET_REPO_SLUG}:${SERVICE}-latest"
                docker build -t $TAG ./${SERVICE}/
                docker push $TAG
              else
                echo "No changes in ${SERVICE}. Skipping."
              fi
            done
