input {
  beats {
    port => 5044
  }
}

filter {
  # message уже содержит сырую строку лога контейнера
  # container.name приходит от filebeat add_docker_metadata
  
  if [container][name] == "nginx-proxy" {
    json {
      source => "message"
      target => "nginx"
      tag_on_failure => ["_nginx_json_parse_failure"]
    }
    
    if "_nginx_json_parse_failure" not in [tags] {
      mutate {
        add_field => { "[@metadata][target_index]" => "nginx-logs" }
        convert   => { "[nginx][status]" => "integer" }
        convert   => { "[nginx][bytes]"  => "integer" }
      }
    }
  } else {
    mutate { add_field => { "[@metadata][target_index]" => "apps-logs" } }
    
    # Пробуем JSON (nodejs/go structured logging)
    json {
      source       => "message"
      target       => "app"
      tag_on_failure => []
    }
  }

  mutate {
    remove_field => ["host", "agent", "ecs", "input"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}-%{+YYYY.MM.dd}"
    manage_template => false
  }
}
