input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    target => "docker_log"
  }

  if [container][name] == "nginx-proxy" {
    json {
      source => "[docker_log][log]"
      target => "nginx"
    }
    mutate { add_field => { "[@metadata][target_index]" => "nginx-logs" } }
  } else {
    mutate { add_field => { "[@metadata][target_index]" => "apps-logs" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}-%{+YYYY.MM.dd}"
    
    # Декларативное управление шаблонами индексов при старте Logstash
    manage_template => true
    template_name => "isdacis-logs"
    template_overwrite => true
    template => "/usr/share/logstash/pipeline/logstash-template.json"
  }
}
