upstream watchtower_backend {
    server watchtower:8080;
}

upstream kibana_backend {
    server kibana:5601;
}

server {
    listen 80;
    

    # Проксирование приложений
    location /go/ { proxy_pass http://go-app:80/; }
    location /nodejs/ { proxy_pass http://nodejs-app:80/; }
    location /python/ { proxy_pass http://python-app:80/; }

    # Защищенный порт Watchtower
    location /v1/update {
        allow 192.168.56.10; # IP вашего GitLab Runner
        deny all;            # Все остальные мимо
        proxy_pass http://watchtower_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /kibana/ {
        proxy_pass http://kibana_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
