log_format json_combined escape=json '{"time":"$time_iso8601","method":"$request_method","uri":"$request_uri","status":$status,"bytes":$body_bytes_sent,"ip":"$remote_addr"}';

upstream watchtower_backend {
    server watchtower:8080;
}

server {
    listen 80;
    
    access_log /dev/stdout json_combined;

    location /go/ { 
        proxy_pass http://go-app:8080/; 
    }
    
    location /nodejs/ { 
        proxy_pass http://nodejs-app:8080/; 
    }
    
    location /python/ { 
        proxy_pass http://python-app:8080/; 
    }

    # Защищенный порт Watchtower
    location /v1/update {
        allow 192.168.56.10; # IP вашего GitLab Runner
        deny all;            # Все остальные мимо
        proxy_pass http://watchtower_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }    
}
